### ISSUE TITLE
Place Foreman client certificates into a peer directory of Foreman checkout

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-katello_devel#265]
Following from https://github.com/theforeman/puppet-katello_devel/pull/264#discussion_r672465771 this feature would move from deploying the client certificates in `/etc/foreman` for development setup to a peer directory of the Foreman checkout. For example:

```
/home/vagrant/foreman
/home/vagrant/foreman-tls
```

Or `foreman-certs` or `certs` or bike-shed-name.

To do this we need to use the technique from https://github.com/theforeman/puppet-certs/pull/370 which deploys from build directory and drops th eneed for the RPMs generated by katello-certs-tools.

**Comment by ekohl** [comment]
I think this can now be closed.
